"""
Полный каталог всех команд Zenith Self-Bot Enterprise (210 команд).
Синхронизируется с REST API сервером и веб-панелью управления.
"""

FULL_COMMANDS_CATALOG = [
    # ─── ИГРЫ И КИБЕР-ЭКОНОМИКА (50 команд) ────────────────────────────────
    {"name": "balance", "category": "Игры", "description": "Просмотр текущего баланса монет и кристаллов", "usage": ".balance", "cooldown": 0},
    {"name": "daily", "category": "Игры", "description": "Ежедневная награда монет (кулдаун 24 часа)", "usage": ".daily", "cooldown": 86400},
    {"name": "work", "category": "Игры", "description": "Работа со случайной киберпанк-профессией и зарплатой", "usage": ".work", "cooldown": 3600},
    {"name": "crime", "category": "Игры", "description": "Опасный налёт на корпорацию с риском получить штраф", "usage": ".crime", "cooldown": 7200},
    {"name": "shop", "category": "Игры", "description": "Магазин оружия, удочек, зелий и артефактов", "usage": ".shop", "cooldown": 0},
    {"name": "buy", "category": "Игры", "description": "Покупка предмета в личный инвентарь SQLite", "usage": ".buy <ID_предмета>", "cooldown": 1},
    {"name": "inventory", "category": "Игры", "description": "Просмотр инвентаря с количеством и иконками предметов", "usage": ".inventory", "cooldown": 0},
    {"name": "transfer", "category": "Игры", "description": "Перевод монет другому пользователю", "usage": ".transfer @user <кол-во>", "cooldown": 1},
    {"name": "rob", "category": "Игры", "description": "Попытка ограбления другого пользователя", "usage": ".rob @user", "cooldown": 10},
    {"name": "mine", "category": "Игры", "description": "Добыча руды и драгоценных металлов в шахте", "usage": ".mine", "cooldown": 2},
    {"name": "blackjack", "category": "Игры", "description": "Карточная игра Блэкджек (21 очко) против дилера", "usage": ".blackjack [ставка]", "cooldown": 2},
    {"name": "casino", "category": "Игры", "description": "Классический игровой автомат (слоты) с джекпотом", "usage": ".casino [ставка]", "cooldown": 2},
    {"name": "dice", "category": "Игры", "description": "Бросок двух игральных кубиков с расчетом суммы", "usage": ".dice [ставка]", "cooldown": 1},
    {"name": "cupgame", "category": "Игры", "description": "Игра в напёрстки (угадай под каким стаканчиком шарик)", "usage": ".cupgame <1-3> [ставка]", "cooldown": 2},
    {"name": "wheel", "category": "Игры", "description": "Колесо фортуны со случайными множителями от 0x до 5x", "usage": ".wheel [ставка]", "cooldown": 2},
    {"name": "coinflip", "category": "Игры", "description": "Подбрасывание монетки (Орёл / Решка)", "usage": ".coinflip [орел/решка] [ставка]", "cooldown": 1},
    {"name": "highlow", "category": "Игры", "description": "Угадывание больше или меньше будет следующее число", "usage": ".highlow <high/low> [ставка]", "cooldown": 1},
    {"name": "roulette", "category": "Игры", "description": "Русская рулетка с револьвером на 6 патронов", "usage": ".roulette", "cooldown": 2},
    {"name": "lottery", "category": "Игры", "description": "Лотерея с выбором числа от 1 до 10 и супер-призом x8", "usage": ".lottery <1-10>", "cooldown": 2},
    {"name": "scratch", "category": "Игры", "description": "Скретч-билет со скрытыми под спойлерами призами", "usage": ".scratch", "cooldown": 1},
    {"name": "darts", "category": "Игры", "description": "Метание дротиков 🎯 в мишень на очки", "usage": ".darts", "cooldown": 1},
    {"name": "bowling", "category": "Игры", "description": "Боулинг 🎳 со сбитием 10 кеглей и страйками", "usage": ".bowling", "cooldown": 1},
    {"name": "football", "category": "Игры", "description": "Футбольный пенальти ⚽ в девятку ворот", "usage": ".football", "cooldown": 1},
    {"name": "basket", "category": "Игры", "description": "Баскетбольный 3-очковый бросок 🏀", "usage": ".basket", "cooldown": 1},
    {"name": "archery", "category": "Игры", "description": "Стрельба из лука по мишени на точность", "usage": ".archery", "cooldown": 1},
    {"name": "fishing", "category": "Игры", "description": "Рыбалка с поимкой редкой рыбы и сокровищ", "usage": ".fishing", "cooldown": 2},
    {"name": "hunt", "category": "Игры", "description": "Охота в диком лесу на редких зверей", "usage": ".hunt", "cooldown": 2},
    {"name": "golf", "category": "Игры", "description": "Гольф с лункой и расчетом ударов", "usage": ".golf", "cooldown": 1},
    {"name": "racing", "category": "Игры", "description": "Кибер-гонки с финишными местами и призами", "usage": ".racing", "cooldown": 2},
    {"name": "boxing", "category": "Игры", "description": "Боксерский поединок на ринге с нокаутом", "usage": ".boxing", "cooldown": 2},
    {"name": "duel", "category": "Игры", "description": "Интерактивная дуэль на реакцию с другим игроком", "usage": ".duel @user", "cooldown": 3},
    {"name": "fight", "category": "Игры", "description": "Текстовая битва с пользователем", "usage": ".fight @user", "cooldown": 2},
    {"name": "dungeon", "category": "Игры", "description": "Поход в темное подземелье за артефактами", "usage": ".dungeon", "cooldown": 3},
    {"name": "bossfight", "category": "Игры", "description": "Рейд на мирового кибер-босса с уроном", "usage": ".bossfight", "cooldown": 5},
    {"name": "pet", "category": "Игры", "description": "Виртуальный питомец (Тамагочи): кормление, игры, сон", "usage": ".pet [feed/play/sleep/инфо]", "cooldown": 1},
    {"name": "lootbox", "category": "Игры", "description": "Открытие лутбокса со случайными скинами", "usage": ".lootbox", "cooldown": 2},
    {"name": "rps", "category": "Игры", "description": "Камень, Ножницы, Бумага против бота", "usage": ".rps <камень/ножницы/бумага>", "cooldown": 1},
    {"name": "tictactoe", "category": "Игры", "description": "Поле для игры в Крестики-Нолики 3x3", "usage": ".tictactoe", "cooldown": 1},
    {"name": "minesweeper", "category": "Игры", "description": "Генератор поля игры Сапёр со скрытыми спойлерами", "usage": ".minesweeper", "cooldown": 1},
    {"name": "heist", "category": "Игры", "description": "Командный налёт на банк", "usage": ".heist", "cooldown": 5},
    {"name": "quiz", "category": "Игры", "description": "Случайный интеллектуальный вопрос викторины", "usage": ".quiz", "cooldown": 1},
    {"name": "typerace", "category": "Игры", "description": "Проверка скорости набора текста", "usage": ".typerace", "cooldown": 1},
    {"name": "slotsmatrix", "category": "Игры", "description": "Слоты Matrix 3x3 с зелеными кибер-символами", "usage": ".slotsmatrix", "cooldown": 2},
    {"name": "magicball", "category": "Игры", "description": "Магический шар судьбы 8-Ball", "usage": ".magicball [вопрос]", "cooldown": 0},
    {"name": "russianroulette_duel", "category": "Игры", "description": "Смертельная дуэль в рулетку между двумя игроками", "usage": ".russianroulette_duel @user", "cooldown": 3},
    {"name": "spin", "category": "Игры", "description": "Вращение виртуального спиннера на время", "usage": ".spin", "cooldown": 1},
    {"name": "slotmachine", "category": "Игры", "description": "Мини игровой автомат в одну строку", "usage": ".slotmachine", "cooldown": 1},
    {"name": "gamble", "category": "Игры", "description": "Гемблинг 50/50 на удвоение любой суммы", "usage": ".gamble <сумма>", "cooldown": 1},
    {"name": "craft", "category": "Игры", "description": "Крафт редких кибер-артефактов в кузнице", "usage": ".craft [предмет]", "cooldown": 2},
    {"name": "guessthenumber", "category": "Игры", "description": "Игра «Угадай число» от 1 до 10 с призом", "usage": ".guessthenumber <число>", "cooldown": 1},

    # ─── КРАСИВОЕ ОФОРМЛЕНИЕ ТЕКСТА И ТИПОГРАФИКА (40 команд) ─────────────
    {"name": "cursive", "category": "Текст", "description": "Красивый рукописный курсивный шрифт (𝓬𝓾𝓻𝓼𝓲𝓿𝓮)", "usage": ".cursive <текст>", "cooldown": 0},
    {"name": "fraktur", "category": "Текст", "description": "Готический средневековый шрифт (𝔉𝔯𝔞𝔨𝔱𝔲𝔯)", "usage": ".fraktur <текст>", "cooldown": 0},
    {"name": "double", "category": "Текст", "description": "Двойной контурный шрифт Blackboard (𝕕𝕠𝕦𝕓𝕝𝕖)", "usage": ".double <текст>", "cooldown": 0},
    {"name": "smallcaps", "category": "Текст", "description": "Капитель — миниатюрные заглавные буквы (sᴍᴀʟʟ ᴄᴀᴘs)", "usage": ".smallcaps <текст>", "cooldown": 0},
    {"name": "bubble", "category": "Текст", "description": "Буквы внутри круглых рамок (ⓑⓤⓑⓑⓛⓔ)", "usage": ".bubble <текст>", "cooldown": 0},
    {"name": "squares", "category": "Текст", "description": "Буквы внутри квадратных рамок (🅂🅀🅄🄰🅁🄴)", "usage": ".squares <текст>", "cooldown": 0},
    {"name": "flip", "category": "Текст", "description": "Переворачивание текста вверх ногами (ʇxǝʇ)", "usage": ".flip <текст>", "cooldown": 0},
    {"name": "vapor", "category": "Текст", "description": "Vaporwave эстетика с широкими буквами (ｖａｐｏｒｗａｖｅ)", "usage": ".vapor <текст>", "cooldown": 0},
    {"name": "superscript", "category": "Текст", "description": "Надстрочный мини-текст (ᵗᵉˣᵗ)", "usage": ".superscript <текст>", "cooldown": 0},
    {"name": "subscript", "category": "Текст", "description": "Подстрочный мини-текст (ₜₑₓₜ)", "usage": ".subscript <текст>", "cooldown": 0},
    {"name": "ansibox", "category": "Текст", "description": "Цветной терминальный блок ANSI (red, green, blue, cyan, etc.)", "usage": ".ansibox <цвет> Заголовок | Текст", "cooldown": 0},
    {"name": "aesthetic", "category": "Текст", "description": "Эстетичный баннер со специальными разделителями", "usage": ".aesthetic <текст>", "cooldown": 0},
    {"name": "neonframe", "category": "Текст", "description": "Светящаяся неоновая рамка для объявлений", "usage": ".neonframe <текст>", "cooldown": 0},
    {"name": "bigquote", "category": "Текст", "description": "Огромная стилизованная цитата с указанием автора", "usage": ".bigquote Автор | Цитата", "cooldown": 0},
    {"name": "fancycard", "category": "Текст", "description": "Стилизованная YAML карточка (Заголовок | Поля)", "usage": ".fancycard Заголовок | Поле 1 | Поле 2", "cooldown": 0},
    {"name": "glitch", "category": "Текст", "description": "Zalgo глитч-эффект наложения символов", "usage": ".glitch <текст>", "cooldown": 0},
    {"name": "crossout", "category": "Текст", "description": "Юникод-зачёркивание каждой буквы", "usage": ".crossout <текст>", "cooldown": 0},
    {"name": "underline", "category": "Текст", "description": "Двойное подчеркивание символов", "usage": ".underline <текст>", "cooldown": 0},
    {"name": "boxedtitle", "category": "Текст", "description": "Компактный заголовок в рамке ┌─[ ТЕКСТ ]─┐", "usage": ".boxedtitle <текст>", "cooldown": 0},
    {"name": "divider", "category": "Текст", "description": "Красивый декоративный разделитель чата", "usage": ".divider", "cooldown": 0},
    {"name": "morse", "category": "Текст", "description": "Преобразование текста в код Морзе", "usage": ".morse <текст>", "cooldown": 0},
    {"name": "binary", "category": "Текст", "description": "Преобразование текста в двоичный 8-битный код", "usage": ".binary <текст>", "cooldown": 0},
    {"name": "hex", "category": "Текст", "description": "Преобразование текста в шестнадцатеричные байты", "usage": ".hex <текст>", "cooldown": 0},
    {"name": "leet", "category": "Текст", "description": "1337 5p34k стиль хакера", "usage": ".leet <текст>", "cooldown": 0},
    {"name": "rot13", "category": "Текст", "description": "ROT13 классический сдвиг", "usage": ".rot13 <текст>", "cooldown": 0},
    {"name": "cipher", "category": "Текст", "description": "Шифр Цезаря со сдвигом N позиций", "usage": ".cipher <сдвиг> <текст>", "cooldown": 0},
    {"name": "reverse", "category": "Текст", "description": "Переворачивание порядка букв задом наперед", "usage": ".reverse <текст>", "cooldown": 0},
    {"name": "mock", "category": "Текст", "description": "Стиль насмешки пРиВеТ кАк ДеЛа", "usage": ".mock <текст>", "cooldown": 0},
    {"name": "spoilerall", "category": "Текст", "description": "Каждая буква в отдельном спойлере ||a||||b||", "usage": ".spoilerall <текст>", "cooldown": 0},
    {"name": "spaced", "category": "Текст", "description": "Текст с увеличенными пробелами между буквами", "usage": ".spaced <текст>", "cooldown": 0},
    {"name": "codeblock", "category": "Текст", "description": "Форматирование кода с подсветкой синтаксиса", "usage": ".codeblock <язык> <код>", "cooldown": 0},
    {"name": "bracket", "category": "Текст", "description": "Японские декоративные скобки 【 ТЕКСТ 】", "usage": ".bracket <текст>", "cooldown": 0},
    {"name": "startext", "category": "Текст", "description": "Текст со звёздным обрамлением ★・──・ ТЕКСТ ・──・★", "usage": ".startext <текст>", "cooldown": 0},
    {"name": "sparkletext", "category": "Текст", "description": "Текст с искрами и блёстками ✧･ﾟ: *✧ ТЕКСТ ✧*:･ﾟ✧", "usage": ".sparkletext <текст>", "cooldown": 0},
    {"name": "hearttext", "category": "Текст", "description": "Текст с сердечным обрамлением ♡ ── ТЕКСТ ── ♡", "usage": ".hearttext <текст>", "cooldown": 0},
    {"name": "arrowbox", "category": "Текст", "description": "Стрелочный баннер »»—— ТЕКСТ ——««", "usage": ".arrowbox <текст>", "cooldown": 0},
    {"name": "bulletlist", "category": "Текст", "description": "Создание маркированного списка через разделитель |", "usage": ".bulletlist Пункт 1 | Пункт 2", "cooldown": 0},
    {"name": "numlist", "category": "Текст", "description": "Создание нумерованного списка через разделитель |", "usage": ".numlist Пункт 1 | Пункт 2", "cooldown": 0},
    {"name": "warnbox", "category": "Текст", "description": "Блок важного предупреждения ⚠️ [ВНИМАНИЕ]", "usage": ".warnbox <текст>", "cooldown": 0},
    {"name": "infobox", "category": "Текст", "description": "Блок информационного сообщения ℹ️ [ИНФО]", "usage": ".infobox <текст>", "cooldown": 0},

    # ─── ПОЛЕЗНЫЕ УТИЛИТЫ И ИНСТРУМЕНТЫ (50 команд) ───────────────────────
    {"name": "notes", "category": "Утилиты", "description": "Просмотр личных сохраненных заметок из SQLite базы", "usage": ".notes", "cooldown": 0},
    {"name": "addnote", "category": "Утилиты", "description": "Сохранение новой заметки в SQLite базу данных", "usage": ".addnote Заголовок | Текст", "cooldown": 0},
    {"name": "delnote", "category": "Утилиты", "description": "Удаление заметки по ID", "usage": ".delnote <ID_заметки>", "cooldown": 0},
    {"name": "remind", "category": "Утилиты", "description": "Установка таймера/напоминания в чат на N секунд", "usage": ".remind <секунды> <сообщение>", "cooldown": 0},
    {"name": "snipe", "category": "Утилиты", "description": "Показ последнего удаленного сообщения в текущем канале", "usage": ".snipe", "cooldown": 0},
    {"name": "editsnipe", "category": "Утилиты", "description": "Показ текста сообщения до редактирования", "usage": ".editsnipe", "cooldown": 0},
    {"name": "afk", "category": "Утилиты", "description": "Включение AFK статуса с автоответчиком в ЛС и пингах", "usage": ".afk [причина]", "cooldown": 0},
    {"name": "unafk", "category": "Утилиты", "description": "Отключение AFK режима", "usage": ".unafk", "cooldown": 0},
    {"name": "shorturl", "category": "Утилиты", "description": "Сокращение длинной ссылки через TinyURL", "usage": ".shorturl <url>", "cooldown": 1},
    {"name": "password", "category": "Утилиты", "description": "Генератор надежного случайного пароля", "usage": ".password [длина]", "cooldown": 0},
    {"name": "calc", "category": "Утилиты", "description": "Математический калькулятор выражений", "usage": ".calc <выражение>", "cooldown": 0},
    {"name": "calcpercent", "category": "Утилиты", "description": "Вычисление процента от числа", "usage": ".calcpercent <часть> <целое>", "cooldown": 0},
    {"name": "hasher", "category": "Утилиты", "description": "Генератор крипто-хешей (MD5, SHA1, SHA256, SHA512)", "usage": ".hasher <алгоритм> <текст>", "cooldown": 0},
    {"name": "pingweb", "category": "Утилиты", "description": "Проверка доступности и задержки любого веб-сайта", "usage": ".pingweb <домен>", "cooldown": 1},
    {"name": "jsonformat", "category": "Утилиты", "description": "Валидация и красивое форматирование JSON данных", "usage": ".jsonformat <json>", "cooldown": 0},
    {"name": "timestamp", "category": "Утилиты", "description": "Генератор Discord Timestamps тегов времени", "usage": ".timestamp [секунды]", "cooldown": 0},
    {"name": "wiki", "category": "Утилиты", "description": "Поиск статьи и краткого резюме по Wikipedia", "usage": ".wiki <запрос>", "cooldown": 1},
    {"name": "qr", "category": "Утилиты", "description": "Генерация QR-кода для любого текста или ссылки", "usage": ".qr <текст>", "cooldown": 1},
    {"name": "weather", "category": "Утилиты", "description": "Погода и температура для любого города мира", "usage": ".weather [город]", "cooldown": 1},
    {"name": "quickpoll", "category": "Утилиты", "description": "Быстрый опрос с реакциями 👍 / 👎", "usage": ".quickpoll <вопрос>", "cooldown": 1},
    {"name": "addcmd", "category": "Утилиты", "description": "Создание пользовательской кастомной команды в SQLite", "usage": ".addcmd <имя> <ответ>", "cooldown": 0},
    {"name": "delcmd", "category": "Утилиты", "description": "Удаление пользовательской кастомной команды", "usage": ".delcmd <имя>", "cooldown": 0},
    {"name": "customcmds", "category": "Утилиты", "description": "Список всех созданных кастомных команд", "usage": ".customcmds", "cooldown": 0},
    {"name": "ping", "category": "Утилиты", "description": "Задержка шлюза Discord API в миллисекундах", "usage": ".ping", "cooldown": 0},
    {"name": "stats", "category": "Утилиты", "description": "Полная статистика работы бота, памяти и API", "usage": ".stats", "cooldown": 0},
    {"name": "uptime", "category": "Утилиты", "description": "Время непрерывной работы бота", "usage": ".uptime", "cooldown": 0},
    {"name": "say", "category": "Утилиты", "description": "Отправка сообщения от имени бота с удалением исходного", "usage": ".say <текст>", "cooldown": 0},
    {"name": "ghostping", "category": "Утилиты", "description": "Скрытый пинг с мгновенным удалением сообщения", "usage": ".ghostping @user", "cooldown": 2},
    {"name": "channelinfo", "category": "Утилиты", "description": "Информация и параметры текущего текстового канала", "usage": ".channelinfo", "cooldown": 0},
    {"name": "serverbanner", "category": "Утилиты", "description": "Баннер текущего сервера во весь размер", "usage": ".serverbanner", "cooldown": 0},
    {"name": "base64encode", "category": "Утилиты", "description": "Кодирование текста в Base64", "usage": ".base64encode <текст>", "cooldown": 0},
    {"name": "base64decode", "category": "Утилиты", "description": "Декодирование строки из Base64", "usage": ".base64decode <base64>", "cooldown": 0},
    {"name": "uuid", "category": "Утилиты", "description": "Генерация уникального UUID v4 идентификатора", "usage": ".uuid", "cooldown": 0},
    {"name": "randomnum", "category": "Утилиты", "description": "Случайное число в заданном диапазоне", "usage": ".randomnum [мин] [макс]", "cooldown": 0},
    {"name": "choose", "category": "Утилиты", "description": "Случайный выбор одного из вариантов через |", "usage": ".choose Вариант 1 | Вариант 2", "cooldown": 0},
    {"name": "length", "category": "Утилиты", "description": "Подсчёт количества символов и слов в тексте", "usage": ".length <текст>", "cooldown": 0},
    {"name": "asciiart", "category": "Утилиты", "description": "Генерация логотипа Zenith в ASCII графике", "usage": ".asciiart", "cooldown": 0},
    {"name": "servericon", "category": "Утилиты", "description": "Прямая ссылка на аватарку сервера", "usage": ".servericon", "cooldown": 0},
    {"name": "calcage", "category": "Утилиты", "description": "Точный возраст аккаунта в днях и годах", "usage": ".calcage [@user]", "cooldown": 0},
    {"name": "translate_en", "category": "Утилиты", "description": "Быстрый перевод текста на английский язык", "usage": ".translate_en <текст>", "cooldown": 1},
    {"name": "colorhex", "category": "Утилиты", "description": "Предпросмотр любого цвета по HEX коду", "usage": ".colorhex <#hex>", "cooldown": 0},
    {"name": "userperms", "category": "Утилиты", "description": "Список прав участника на сервере", "usage": ".userperms [@user]", "cooldown": 0},
    {"name": "rolecount", "category": "Утилиты", "description": "Количество ролей на текущем сервере", "usage": ".rolecount", "cooldown": 0},
    {"name": "emojicount", "category": "Утилиты", "description": "Количество эмодзи на текущем сервере", "usage": ".emojicount", "cooldown": 0},
    {"name": "firstmessage", "category": "Утилиты", "description": "Ссылка для перехода к первому сообщению канала", "usage": ".firstmessage", "cooldown": 0},
    {"name": "clearmylog", "category": "Утилиты", "description": "Очистка локального журнала событий SQLite", "usage": ".clearmylog", "cooldown": 0},
    {"name": "dbstatus", "category": "Утилиты", "description": "Проверка статуса подключения базы SQLite", "usage": ".dbstatus", "cooldown": 0},
    {"name": "testconnection", "category": "Утилиты", "description": "Тест сквозной связи Панель ➔ Бот ➔ Gateway", "usage": ".testconnection", "cooldown": 0},
    {"name": "epoch", "category": "Утилиты", "description": "Текущее время в формате Unix Epoch", "usage": ".epoch", "cooldown": 0},
    {"name": "copyemoji", "category": "Утилиты", "description": "Копирование эмодзи с другого сервера и загрузка на текущий", "usage": ".copyemoji <эмодзи/ID> [имя]", "cooldown": 2},
    {"name": "help", "category": "Утилиты", "description": "Главный интерактивный справочник по командам", "usage": ".help", "cooldown": 0},

    # ─── OSINT И СБОР ДАННЫХ ПО ID (25 команд) ─────────────────────────────
    {"name": "fetch", "category": "OSINT", "description": "Глубокий сбор данных профиля Discord по Snowflake ID", "usage": ".fetch <ID>", "cooldown": 1},
    {"name": "fetchavatar", "category": "OSINT", "description": "Аватарка пользователя по ID во всех форматах (PNG, WEBP, GIF)", "usage": ".fetchavatar <ID>", "cooldown": 1},
    {"name": "fetchbanner", "category": "OSINT", "description": "Баннер профиля пользователя по ID", "usage": ".fetchbanner <ID>", "cooldown": 1},
    {"name": "fetchbadges", "category": "OSINT", "description": "Значки и бейджи профиля по ID", "usage": ".fetchbadges <ID>", "cooldown": 1},
    {"name": "mutuals", "category": "OSINT", "description": "Поиск общих серверов с пользователем", "usage": ".mutuals @user", "cooldown": 2},
    {"name": "checkbot", "category": "OSINT", "description": "Проверка бота по ID и генерация OAuth2 инвайта", "usage": ".checkbot <ID_бота>", "cooldown": 1},
    {"name": "nitrocheck", "category": "OSINT", "description": "Анализ наличия активного Nitro по признакам профиля", "usage": ".nitrocheck <ID>", "cooldown": 1},
    {"name": "idtime", "category": "OSINT", "description": "Декодирование даты создания Discord Snowflake ID", "usage": ".idtime <ID>", "cooldown": 0},
    {"name": "guildfetch", "category": "OSINT", "description": "Сбор публичной информации о сервере по ID", "usage": ".guildfetch <ID_сервера>", "cooldown": 1},
    {"name": "userinfo", "category": "OSINT", "description": "Подробная информация об участнике сервера", "usage": ".userinfo [@user]", "cooldown": 0},
    {"name": "serverinfo", "category": "OSINT", "description": "Сводка о сервере, бустах, владельце и каналах", "usage": ".serverinfo", "cooldown": 0},
    {"name": "avatar", "category": "OSINT", "description": "Аватарка участника сервера в высоком разрешении", "usage": ".avatar [@user]", "cooldown": 0},
    {"name": "roles", "category": "OSINT", "description": "Список всех ролей сервера с количеством участников", "usage": ".roles", "cooldown": 0},
    {"name": "emojis", "category": "OSINT", "description": "Список всех эмодзи сервера", "usage": ".emojis", "cooldown": 0},
    {"name": "invites", "category": "OSINT", "description": "Аудит активных приглашений сервера", "usage": ".invites", "cooldown": 1},
    {"name": "auditbots", "category": "OSINT", "description": "Список всех ботов на текущем сервере с ID", "usage": ".auditbots", "cooldown": 1},
    {"name": "auditbans", "category": "OSINT", "description": "Просмотр бан-листа сервера", "usage": ".auditbans", "cooldown": 1},
    {"name": "whois", "category": "OSINT", "description": "Краткая справка по пользователю через Discord API", "usage": ".whois <ID>", "cooldown": 1},
    {"name": "channelid", "category": "OSINT", "description": "Получение ID текущего текстового канала", "usage": ".channelid", "cooldown": 0},
    {"name": "guildid", "category": "OSINT", "description": "Получение ID текущего сервера", "usage": ".guildid", "cooldown": 0},
    {"name": "checkvoice", "category": "OSINT", "description": "Проверка нахождения участника в голосовом канале", "usage": ".checkvoice [@user]", "cooldown": 0},
    {"name": "rolemembers", "category": "OSINT", "description": "Список участников с определенной ролью", "usage": ".rolemembers @роль", "cooldown": 0},
    {"name": "fetchcreated", "category": "OSINT", "description": "Точная дата регистрации аккаунта по ID", "usage": ".fetchcreated <ID>", "cooldown": 0},
    {"name": "serverage", "category": "OSINT", "description": "Возраст сервера со дня основания", "usage": ".serverage", "cooldown": 0},
    {"name": "ownerinfo", "category": "OSINT", "description": "Информация о владельце текущего сервера", "usage": ".ownerinfo", "cooldown": 0},

    # ─── МОДЕРАЦИЯ И СИСТЕМА ВАРНОВ (20 команд) ───────────────────────────
    {"name": "warn", "category": "Модерация", "description": "Выдача варна (при 4/4 — автоматический мут на 1 час)", "usage": ".warn <@user/ID> [причина]", "cooldown": 1},
    {"name": "warns", "category": "Модерация", "description": "Просмотр всех предупреждений пользователя с ID и датами", "usage": ".warns [@user/ID]", "cooldown": 0},
    {"name": "clearwarns", "category": "Модерация", "description": "Полное снятие всех варнов с пользователя", "usage": ".clearwarns <@user/ID>", "cooldown": 1},
    {"name": "delwarn", "category": "Модерация", "description": "Удаление конкретного предупреждения по ID", "usage": ".delwarn <ID_варна>", "cooldown": 0},
    {"name": "kick", "category": "Модерация", "description": "Исключение участника с сервера", "usage": ".kick @user [причина]", "cooldown": 1},
    {"name": "ban", "category": "Модерация", "description": "Блокировка участника на сервере", "usage": ".ban @user [причина]", "cooldown": 1},
    {"name": "unban", "category": "Модерация", "description": "Разблокировка пользователя по ID", "usage": ".unban <ID_пользователя>", "cooldown": 1},
    {"name": "mute", "category": "Модерация", "description": "Выдача тайм-аута (мута) на N минут", "usage": ".mute @user [минуты] [причина]", "cooldown": 1},
    {"name": "unmute", "category": "Модерация", "description": "Снятие тайм-аута с участника", "usage": ".unmute @user", "cooldown": 1},
    {"name": "purge", "category": "Модерация", "description": "Удаление собственных сообщений в текущем канале", "usage": ".purge [кол-во]", "cooldown": 2},
    {"name": "slowmode", "category": "Модерация", "description": "Установка медленного режима (Slowmode) в секундах", "usage": ".slowmode <секунды>", "cooldown": 1},
    {"name": "lock", "category": "Модерация", "description": "Блокировка отправки сообщений в текущем канале", "usage": ".lock", "cooldown": 1},
    {"name": "unlock", "category": "Модерация", "description": "Разблокировка отправки сообщений в канале", "usage": ".unlock", "cooldown": 1},
    {"name": "addrole", "category": "Модерация", "description": "Выдача роли участнику сервера", "usage": ".addrole @user @роль", "cooldown": 1},
    {"name": "removerole", "category": "Модерация", "description": "Снятие роли с участника сервера", "usage": ".removerole @user @роль", "cooldown": 1},
    {"name": "nick", "category": "Модерация", "description": "Смена собственного никнейма на сервере", "usage": ".nick <новый_ник>", "cooldown": 1},
    {"name": "setoutput", "category": "Модерация", "description": "Назначение канала вывода ответов бота для сервера", "usage": ".setoutput #канал", "cooldown": 0},
    {"name": "purgewords", "category": "Модерация", "description": "Удаление своих сообщений, содержащих указанное слово", "usage": ".purgewords <слово> [лимит]", "cooldown": 2},
    {"name": "modlogs", "category": "Модерация", "description": "Журнал последних действий модерации из базы данных", "usage": ".modlogs", "cooldown": 0},
    {"name": "massrole", "category": "Модерация", "description": "Массовое назначение роли", "usage": ".massrole @роль", "cooldown": 5},

    # ─── УНИКАЛЬНЫЕ И АВТОРСКИЕ (25 команд) ───────────────────────────────
    {"name": "copyemoji", "category": "Уникальные", "description": "Копирование эмодзи с любого сервера в текущий по ссылке или ID", "usage": ".copyemoji <ID / <:name:id> / URL>", "cooldown": 2},
    {"name": "crypto", "category": "Уникальные", "description": "Курсы BTC, ETH, TON, SOL и курс USD/RUB с трендовым графиком", "usage": ".crypto", "cooldown": 1},
    {"name": "spotify", "category": "Уникальные", "description": "Интерактивная карточка прослушивания Spotify с прогресс-баром", "usage": ".spotify", "cooldown": 0},
    {"name": "secretmsg", "category": "Уникальные", "description": "Шифрование секретного сообщения с защитой паролем", "usage": ".secretmsg <пароль> <текст>", "cooldown": 0},
    {"name": "clonemsg", "category": "Уникальные", "description": "Клонирование чужого сообщения в текущий чат по ID", "usage": ".clonemsg <ID_сообщения>", "cooldown": 0},
    {"name": "magicembed", "category": "Уникальные", "description": "Псевдо-эмбед с неоновыми рамками", "usage": ".magicembed Заголовок | Текст", "cooldown": 0},
    {"name": "reactall", "category": "Уникальные", "description": "Массовая установка реакции на последние N сообщений", "usage": ".reactall <кол-во> <эмодзи>", "cooldown": 2},
    {"name": "fakeactivity", "category": "Уникальные", "description": "Кастомный статус игры в Discord профиле", "usage": ".fakeactivity <название игры>", "cooldown": 0},
    {"name": "stealthmode", "category": "Уникальные", "description": "Активация режима невидимки (Invisible)", "usage": ".stealthmode", "cooldown": 0},
    {"name": "status", "category": "Уникальные", "description": "Смена статуса (online, idle, dnd, invisible)", "usage": ".status <online/idle/dnd/invisible>", "cooldown": 0},
    {"name": "stream", "category": "Уникальные", "description": "Включение стримингового фиолетового статуса", "usage": ".stream <название>", "cooldown": 0},
    {"name": "clearstatus", "category": "Уникальные", "description": "Сброс активности и статуса", "usage": ".clearstatus", "cooldown": 0},
    {"name": "synctime", "category": "Уникальные", "description": "Точное мировое время (MSK, UTC, EST, Tokyo)", "usage": ".synctime", "cooldown": 0},
    {"name": "asciitext", "category": "Уникальные", "description": "Большой ASCII баннер из символов", "usage": ".asciitext <текст>", "cooldown": 0},
    {"name": "rainbowreact", "category": "Уникальные", "description": "Установка радуги реакций 🌈 на сообщение", "usage": ".rainbowreact <ID_сообщения>", "cooldown": 2},
    {"name": "quickpurge", "category": "Уникальные", "description": "Молниеносная очистка последних 5 своих сообщений", "usage": ".quickpurge", "cooldown": 1},
    {"name": "typing", "category": "Уникальные", "description": "Имитация непрерывного набора текста на N секунд", "usage": ".typing [секунды]", "cooldown": 2},
    {"name": "quote", "category": "Уникальные", "description": "Цитирование любого сообщения по ID с автором", "usage": ".quote <ID_сообщения>", "cooldown": 0},
    {"name": "selfinfo", "category": "Уникальные", "description": "Информация об авторизованном профиле селф-бота", "usage": ".selfinfo", "cooldown": 0},
    {"name": "echo", "category": "Уникальные", "description": "Эхо-повтор текста", "usage": ".echo <текст>", "cooldown": 0},
    {"name": "reverseecho", "category": "Уникальные", "description": "Эхо-повтор текста задом наперёд", "usage": ".reverseecho <текст>", "cooldown": 0},
    {"name": "copylink", "category": "Уникальные", "description": "Генератор прямой ссылки на сообщение по ID", "usage": ".copylink <ID_сообщения>", "cooldown": 0},
    {"name": "markread", "category": "Уникальные", "description": "Пометить канал прочитанным", "usage": ".markread", "cooldown": 0},
    {"name": "serverchannels", "category": "Уникальные", "description": "Быстрый список каналов сервера", "usage": ".serverchannels", "cooldown": 0},
    {"name": "zenithver", "category": "Уникальные", "description": "Версия ядра Zenith Enterprise Engine", "usage": ".zenithver", "cooldown": 0},
    {"name": "streamroll", "category": "Уникальные", "description": "Смена и случайная ротация названия стрима", "usage": ".streamroll [название]", "cooldown": 0},
    {"name": "displayname", "category": "Модерация", "description": "Смена глобального отображаемого имени профиля", "usage": ".displayname <имя>", "cooldown": 2},
    {"name": "clearslowmode", "category": "Модерация", "description": "Мгновенное снятие медленного режима с канала", "usage": ".clearslowmode", "cooldown": 1},

    # ─── ИСКУССТВЕННЫЙ ИНТЕЛЛЕКТ (AI) ─────────────────────────────────────
    {"name": "ai", "category": "ИИ", "description": "Прямой запрос к искусственному интеллекту DeepSeek V4-Flash", "usage": ".ai <вопрос или задача>", "cooldown": 5},
    {"name": "aimode", "category": "ИИ", "description": "Включение/выключение умного AI автоответчика в текущем канале", "usage": ".aimode", "cooldown": 0},
    {"name": "aiclear", "category": "ИИ", "description": "Очистка контекста диалога с нейросетью в текущем канале", "usage": ".aiclear", "cooldown": 0},
    {"name": "aimodels", "category": "ИИ", "description": "Параметры и архитектура нейросети Zenith AI", "usage": ".aimodels", "cooldown": 0}
]
